### ISSUE TITLE
Keyboard events broken

### ISSUE THREAD

**Issue by ThatOneCheetah** [Rusketh/ExpAdv2#289]
**1.** Hold key *A*
**2.** Hold key *B*
**3.** keyrelease is called for key *A* even though it is still being held
**4.** Release key *B*
**5.** keyrelease is called for key *B* (expected) but keypressed is now called for key *A*

Further inspection reveals that keypress is being called twice, with a keyrelease inbetween those times, as well.

**Comment by VINTproYKT** [comment]
Hm, I don't see such problem, all works as expected.

```
server {
    number key_N = "n".toByte()
    number key_M = "m".toByte()

    event keypress( player Ply, number Key ) {
        if ( Key == key_N ) {
            print( "Pressed N" )
        }
        elseif ( Key == key_M ) {
            print( "Pressed M" )
        }
    }
    event keyrelease( player Ply, number Key ) {
        if ( Key == key_N ) {
            print( "Released N" )
        }
        elseif ( Key == key_M ) {
            print( "Released M" )
        }
    }
}
```

Have you tried other code?

**Comment by MaZyGer** [comment]
I have problems too. I just tested onNumpad delegates. I get with one press 2-3 calls and also a or two calls if I release it.

is pretty annyoing and random.

keypress is same

**Comment by ThatOneCheetah** [comment]
Forgot to memtion I was hooking the events on clientside as well, this is possibly a clientside only thing.

**Comment by VINTproYKT** [comment]
Any posibilities why it's going on? I have no this problem on clientside.

**Comment by MaZyGer** [comment]
oh there was not much. I wanted just test. I am not ingame but it was like:
```
client {
	onNumpadZero(function(player ply) {
		if(ply == owner()) {
			print("It was me");
		}
	});
}
```
It get called on press sometimes two times and after I release the key again.
I was playing on a server. They use Workshop I guess (because I saw the download info that I am downloading it from workshop). Maybe they got buggy version :P

**Comment by ThatOneCheetah** [comment]
How can you add wontfix to something this important?
I might as well fork it and see if I can fix it myself.

**Comment by Rusketh** [comment]
I believe I have just fixed this, can anybody confirm. I am at work so I cant :(

**Comment by AkitakeKun** [comment]
I've just tested it with codes similar to the ones above, they work just fine and functions don't get called twice serverside, but nothing seems to work clientside.

**Comment by ArmyArmyCz** [comment]
onNumpadZero seems to work fine, but the keypressed event is still broken.

**Comment by bigdogmat** [comment]
This is caused by https://github.com/Facepunch/garrysmod-issues/issues/418

**Comment by willox** [comment]
I tried to test your issue and it seems to be fixed on my local build of gmod. I don't know anything about ExpAdv2 but I used the following code (i have no numpad!):

```cpp
client {
    event keypress( player Ply, number Key ) {
        print( Key + " down." )
    }
    
    event keyrelease( player Ply, number Key ) {
        print( Key + " up." )
    }
}
```
